version: '3'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=bankaccountdb
      - TZ=UTC
    ports:
      - "5433:5432"
