name: Gradle check

on: [push]

jobs:
  gradle-build:
    runs-on: ubuntu-18.04
    services:
      database:
        image: postgres:11.2-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: bankaccountdb
          TZ: UTC
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache Gradle dependencies
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches/modules-2
        key: ${{ runner.os }}-gradle-modules-${{ hashFiles('**/*gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-modules-

    - name: Build with Gradle
      env:
        DB_URL: "jdbc:postgresql://localhost:5432/bankaccountdb"
        PROJEKTOR_TOKEN: ${{ secrets.PROJEKTOR_TOKEN }}
      run: |
        chmod +x ./gradlew
        ./gradlew check

    - name: Projektor report URL
      uses: craigatk/projektor-action@v10
      if: failure() || success()
      with:
        print-link: true
