name: Gradle check

on: [push]

jobs:
  gradle-build:
    runs-on: ubuntu-18.04

    services:
      database:
        image: postgres:11.2-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: bankaccountdb
          TZ: UTC
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        java: [11, 17]

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
        cache: 'gradle'

    - name: Build with Gradle
      env:
        DB_URL: "jdbc:postgresql://localhost:5432/bankaccountdb"
        PROJEKTOR_TOKEN: ${{ secrets.PROJEKTOR_TOKEN }}
      run: |
        ./gradlew check

    - name: Projektor report URL
      uses: craigatk/projektor-action@v10
      if: failure() || success()
      with:
        print-link: true
